### ISSUE TITLE
Chrome Dev

### ISSUE THREAD

**Issue by ryanjmchale** [Nithanim/ChromeBatteryApiFake#1]
Under the latest build of Chrome on Android 6.0.1 (n920c). The module does not appear to block the API. Confirmed working under Chrome build 51.

https://steveedson.co.uk/html5/battery-api/  used for testing. 

Chrome version: 53.0. 2785.44

**Comment by Nithanim** [comment]
So after wasting some time I realized that I only had to add that package name of chrome-dev.
Thank you for your report!
